// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Gxpry3Dvx6Fc9E7_tVPNBoPmc_qdPKA',
    appId: '1:103255790407:web:c27cd392e001e805257262',
    messagingSenderId: '103255790407',
    projectId: 'blood-853d2',
    authDomain: 'blood-853d2.firebaseapp.com',
    storageBucket: 'blood-853d2.appspot.com',
    measurementId: 'G-YPT9D605SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjw5DhXpOQpZVEs-Hp16LK-w3DlCVZPRc',
    appId: '1:103255790407:android:bc8223a74a43ab45257262',
    messagingSenderId: '103255790407',
    projectId: 'blood-853d2',
    storageBucket: 'blood-853d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGIkViQxKczKpr0pNdoBcRnhSb5uY6uDY',
    appId: '1:103255790407:ios:528d0a3e67495a33257262',
    messagingSenderId: '103255790407',
    projectId: 'blood-853d2',
    storageBucket: 'blood-853d2.appspot.com',
    iosBundleId: 'com.example.bloodnation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGIkViQxKczKpr0pNdoBcRnhSb5uY6uDY',
    appId: '1:103255790407:ios:a186b47d3fe7fedd257262',
    messagingSenderId: '103255790407',
    projectId: 'blood-853d2',
    storageBucket: 'blood-853d2.appspot.com',
    iosBundleId: 'com.example.bloodnation.RunnerTests',
  );
}
